In [89]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re

In [90]:
df = pd.read_csv('filling_missing_values.csv')
df.head()

,Unnamed: 0,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,rom,hdmi_port,Spec_Score,Company,usb_port
0,0,1,tcl,1,0,42999,4.65,55.0,qled,3840.0,2160.0,1,20.0,2.0,16.0,1,58.0,flipkart,2.0
1,1,2,lg,1,0,41999,4.55,55.0,led,3840.0,2160.0,1,20.0,2.0,19.2,1,55.0,flipkart,1.0
2,2,3,xiaomi,1,0,36999,4.35,55.0,qled,3840.0,2160.0,1,34.0,2.0,32.0,1,55.0,amazon,2.0
3,3,4,lg,1,0,30999,4.40,43.0,led,3840.0,2160.0,1,20.0,2.0,19.2,1,52.0,flipkart,1.0
4,4,5,philips,1,0,74999,4.05,75.0,qled,3840.0,2160.0,1,30.0,2.0,32.0,1,67.0,amazon,2.0

In [91]:
df1 = df.copy()
df1.head()

,Unnamed: 0,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,rom,hdmi_port,Spec_Score,Company,usb_port
0,0,1,tcl,1,0,42999,4.65,55.0,qled,3840.0,2160.0,1,20.0,2.0,16.0,1,58.0,flipkart,2.0
1,1,2,lg,1,0,41999,4.55,55.0,led,3840.0,2160.0,1,20.0,2.0,19.2,1,55.0,flipkart,1.0
2,2,3,xiaomi,1,0,36999,4.35,55.0,qled,3840.0,2160.0,1,34.0,2.0,32.0,1,55.0,amazon,2.0
3,3,4,lg,1,0,30999,4.40,43.0,led,3840.0,2160.0,1,20.0,2.0,19.2,1,52.0,flipkart,1.0
4,4,5,philips,1,0,74999,4.05,75.0,qled,3840.0,2160.0,1,30.0,2.0,32.0,1,67.0,amazon,2.0

In [92]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1000 non-null   int64
 1   index              1000 non-null   int64
 2   brand              1000 non-null   object
 3   ultra_hd           1000 non-null   int64
 4   full_hd            1000 non-null   int64
 5   Price              1000 non-null   int64
 6   Rating             1000 non-null   float64
 7   inches             1000 non-null   float64
 8   display_type       1000 non-null   object
 9   resolution_width   1000 non-null   float64
 10  resolution_height  1000 non-null   float64
 11  wifi               1000 non-null   int64
 12  fast_charging      1000 non-null   float64
 13  ram                1000 non-null   float64
 14  rom                1000 non-null   float64
 15  hdmi_port          1000 non-null   int64
 16  Spec_Score         1000 non-null   float64
 17  Company            1000 non-null   object
 18  usb_port           1000 non-null   float64
dtypes: float64(9), int64(7), object(3)
memory usage: 148.6+ KB

In [93]:
df1.drop(columns=['Unnamed: 0'], inplace=True)

In [94]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   int64
 3   full_hd            1000 non-null   int64
 4   Price              1000 non-null   int64
 5   Rating             1000 non-null   float64
 6   inches             1000 non-null   float64
 7   display_type       1000 non-null   object
 8   resolution_width   1000 non-null   float64
 9   resolution_height  1000 non-null   float64
 10  wifi               1000 non-null   int64
 11  fast_charging      1000 non-null   float64
 12  ram                1000 non-null   float64
 13  rom                1000 non-null   float64
 14  hdmi_port          1000 non-null   int64
 15  Spec_Score         1000 non-null   float64
 16  Company            1000 non-null   object
 17  usb_port           1000 non-null   float64
dtypes: float64(9), int64(6), object(3)
memory usage: 140.8+ KB

In [95]:
df1['ultra_hd'].value_counts()

ultra_hd
1    757
0    243
Name: count, dtype: int64

In [96]:
df1['full_hd'].value_counts()

full_hd
0    911
1     89
Name: count, dtype: int64

In [97]:
df1['Rating'].value_counts()

Rating
4.75    75
4.25    72
4.00    70
4.55    68
4.35    68
4.30    68
4.20    65
4.45    64
4.65    62
4.05    60
4.60    60
4.15    56
4.40    55
4.50    55
4.70    54
4.10    48
Name: count, dtype: int64

In [98]:
df1['inches'].value_counts()

inches
55.00     220
43.00     195
65.00     164
32.00     146
75.00      93
50.00      81
85.00      24
40.00      23
24.00      15
77.00       8
98.00       7
100.00      6
48.00       3
86.00       3
31.50       2
120.00      1
23.62       1
54.72       1
39.37       1
42.52       1
31.89       1
115.00      1
83.00       1
49.00       1
58.00       1
Name: count, dtype: int64

In [99]:
df1['resolution_width'].value_counts()

resolution_width
3840.0    754
1920.0    241
7680.0      4
3664.0      1
Name: count, dtype: int64

In [100]:
df1['resolution_height'].value_counts()

resolution_height
2160.000000    753
768.000000     156
1080.000000     85
4320.000000      4
1858.784353      1
1665.600000      1
Name: count, dtype: int64

In [101]:
df1['wifi'].value_counts()

wifi
1    957
0     43
Name: count, dtype: int64

In [102]:
df1['fast_charging'].value_counts()

fast_charging
20.000000    466
30.000000    165
24.000000     87
40.000000     69
60.000000     36
36.000000     28
48.000000     26
50.000000     23
70.000000     18
10.000000     11
16.000000     11
35.000000     10
34.000000     10
26.000000      7
80.000000      6
88.000000      5
8.000000       4
49.000000      3
44.000000      2
32.000000      2
24.800000      1
4.000000       1
56.000000      1
12.000000      1
28.723232      1
54.000000      1
28.400000      1
25.000000      1
90.000000      1
22.000000      1
28.800000      1
Name: count, dtype: int64

In [103]:
df1['rom'].value_counts()

rom
16.0    353
19.2    205
32.0    171
22.4    107
25.6     51
28.8     31
44.8     21
64.0     20
38.4     15
35.2      8
57.6      6
41.6      6
51.2      5
25.5      1
Name: count, dtype: int64

In [104]:
df1['ram'].value_counts()

ram
2.000000    448
3.000000    103
2.600000     86
1.000000     83
1.800000     68
2.200000     49
2.800000     43
2.400000     40
5.000000     35
3.400000     17
3.200000     12
3.800000      5
1.400000      4
4.000000      3
1.600000      2
2.209932      1
4.200000      1
Name: count, dtype: int64

In [105]:
df1['hdmi_port'].value_counts()

hdmi_port
1    995
0      5
Name: count, dtype: int64

In [106]:
df1['usb_port'].value_counts()

usb_port
2.000000    730
1.000000    227
3.000000     33
1.600000      3
1.400000      3
1.800000      2
1.805274      1
4.000000      1
Name: count, dtype: int64

In [107]:
df1['Spec_Score'].value_counts()

Spec_Score
55.000000    55
31.000000    31
56.000000    30
52.000000    28
67.000000    28
54.000000    27
58.000000    26
57.000000    26
43.000000    25
66.000000    25
35.000000    25
53.000000    25
51.000000    24
36.000000    24
38.000000    22
63.000000    22
62.000000    22
50.000000    22
46.000000    21
37.000000    21
48.000000    21
59.000000    21
60.000000    20
45.000000    19
61.000000    18
42.000000    17
80.000000    16
40.000000    15
47.000000    15
49.000000    15
64.000000    14
34.000000    13
33.000000    13
70.000000    13
78.000000    13
39.000000    13
81.000000    12
82.000000    12
71.000000    12
68.000000    12
73.000000    12
77.000000    12
74.000000    11
65.000000    11
44.000000    10
76.000000    10
69.000000     9
72.000000     9
41.000000     9
79.000000     9
32.000000     8
84.000000     7
30.000000     7
75.000000     6
21.000000     6
85.000000     4
83.000000     4
19.000000     3
87.000000     3
20.000000     3
26.000000     2
29.000000     2
18.000000     2
55.200000     1
25.000000     1
22.000000     1
54.300601     1
86.000000     1
92.000000     1
91.000000     1
28.000000     1
Name: count, dtype: int64

In [108]:
df1['brand'].value_counts()

brand
samsung         171
tcl              94
lg               94
hisense          48
sony             47
xiaomi           35
haier            34
realme           32
croma            31
toshiba          26
blaupunkt        24
thomson          22
motorola         22
acer             21
onida            20
foxsky           18
vw               17
vu               17
sansui           17
kodak            16
coocaa           14
philips          14
wobble           13
panasonic        13
iffalcon         12
uniboom          10
reliance         10
infinix           8
acerpure          8
lumio             7
metz              7
beston            7
innoq             6
lloyd             5
bush              5
rgl               5
nu                5
bpl               5
vzy               5
marq              4
nacson            3
ifflacon          3
kenstar           3
blackdecker       3
tseries           3
compaq            2
akai              2
elista            2
skylive           2
kodal             1
aiwa              1
hyundai           1
westinghouse      1
beethosol         1
xelectron         1
redmi             1
bazeegar          1
Name: count, dtype: int64

In [109]:
df1['display_type'].value_counts()

display_type
led        444
qled       391
miniled    111
oled        41
micro        5
qned         5
lcd          2
laser        1
Name: count, dtype: int64

In [110]:
df1['Company'].value_counts()

Company
flipkart    570
amazon      267
croma       163
Name: count, dtype: int64

In [111]:
df1['fast_charging'].min()

4.0

In [112]:
def fast_charging(x):
    if x <= 30:
        return 'slow'
    elif x >=30 and x <= 60:
        return 'medium'
    else:
        return 'high'
        
charging = df1['fast_charging'].apply(fast_charging)
model_pos = df1.columns.get_loc('ram')
df1.insert(model_pos, 'charging_category', charging)

In [113]:
df1['charging_category'].value_counts()

charging_category
slow      759
medium    211
high       30
Name: count, dtype: int64

In [114]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,charging_category,ram,rom,hdmi_port,Spec_Score,Company,usb_port
0,1,tcl,1,0,42999,4.65,55.0,qled,3840.0,2160.0,1,20.0,slow,2.0,16.0,1,58.0,flipkart,2.0
1,2,lg,1,0,41999,4.55,55.0,led,3840.0,2160.0,1,20.0,slow,2.0,19.2,1,55.0,flipkart,1.0
2,3,xiaomi,1,0,36999,4.35,55.0,qled,3840.0,2160.0,1,34.0,medium,2.0,32.0,1,55.0,amazon,2.0
3,4,lg,1,0,30999,4.40,43.0,led,3840.0,2160.0,1,20.0,slow,2.0,19.2,1,52.0,flipkart,1.0
4,5,philips,1,0,74999,4.05,75.0,qled,3840.0,2160.0,1,30.0,slow,2.0,32.0,1,67.0,amazon,2.0

In [115]:
df1['display_type'].value_counts()

display_type
led        444
qled       391
miniled    111
oled        41
micro        5
qned         5
lcd          2
laser        1
Name: count, dtype: int64

In [116]:
col = df1.pop('hdmi_port')
df1.insert(17, 'hdmi_port', col)

In [117]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,charging_category,ram,rom,Spec_Score,Company,hdmi_port,usb_port
0,1,tcl,1,0,42999,4.65,55.0,qled,3840.0,2160.0,1,20.0,slow,2.0,16.0,58.0,flipkart,1,2.0
1,2,lg,1,0,41999,4.55,55.0,led,3840.0,2160.0,1,20.0,slow,2.0,19.2,55.0,flipkart,1,1.0
2,3,xiaomi,1,0,36999,4.35,55.0,qled,3840.0,2160.0,1,34.0,medium,2.0,32.0,55.0,amazon,1,2.0
3,4,lg,1,0,30999,4.40,43.0,led,3840.0,2160.0,1,20.0,slow,2.0,19.2,52.0,flipkart,1,1.0
4,5,philips,1,0,74999,4.05,75.0,qled,3840.0,2160.0,1,30.0,slow,2.0,32.0,67.0,amazon,1,2.0

In [118]:
ppi = np.sqrt(df1['resolution_width'] **2 +
df1['resolution_height'] ** 2 /
df1['inches'])

model_pos = df1.columns.get_loc('resolution_width')
df1.insert(model_pos, 'ppi', ppi)

In [119]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,ppi,resolution_width,resolution_height,wifi,fast_charging,charging_category,ram,rom,Spec_Score,Company,hdmi_port,usb_port
0,1,tcl,1,0,42999,4.65,55.0,qled,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,16.0,58.0,flipkart,1,2.0
1,2,lg,1,0,41999,4.55,55.0,led,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,19.2,55.0,flipkart,1,1.0
2,3,xiaomi,1,0,36999,4.35,55.0,qled,3851.029614,3840.0,2160.0,1,34.0,medium,2.0,32.0,55.0,amazon,1,2.0
3,4,lg,1,0,30999,4.40,43.0,led,3854.102013,3840.0,2160.0,1,20.0,slow,2.0,19.2,52.0,flipkart,1,1.0
4,5,philips,1,0,74999,4.05,75.0,qled,3848.091475,3840.0,2160.0,1,30.0,slow,2.0,32.0,67.0,amazon,1,2.0

In [120]:
df1['value_score'] = (df1['Spec_Score'] * df1['Rating']) / df1['Price']

In [121]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [122]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,ppi,resolution_width,resolution_height,wifi,fast_charging,charging_category,ram,rom,Spec_Score,Company,hdmi_port,usb_port,value_score
0,1,tcl,1,0,42999,4.65,55.0,qled,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,16.0,58.0,flipkart,1,2.0,0.006272
1,2,lg,1,0,41999,4.55,55.0,led,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,19.2,55.0,flipkart,1,1.0,0.005958
2,3,xiaomi,1,0,36999,4.35,55.0,qled,3851.029614,3840.0,2160.0,1,34.0,medium,2.0,32.0,55.0,amazon,1,2.0,0.006466
3,4,lg,1,0,30999,4.40,43.0,led,3854.102013,3840.0,2160.0,1,20.0,slow,2.0,19.2,52.0,flipkart,1,1.0,0.007381
4,5,philips,1,0,74999,4.05,75.0,qled,3848.091475,3840.0,2160.0,1,30.0,slow,2.0,32.0,67.0,amazon,1,2.0,0.003618

In [123]:
df1['inches'].min()

23.62

In [124]:
def inches(x):
    if x==23 and x<=50:
        return 'small'
    elif x >= 50 and x <= 80:
        return 'medium'
    else:
        return 'high'
    
cat = df1['inches'].apply(inches)
model_pos = df1.columns.get_loc('inches')
df1.insert(model_pos, 'size_category', cat)

In [125]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,size_category,inches,display_type,ppi,resolution_width,resolution_height,wifi,fast_charging,charging_category,ram,rom,Spec_Score,Company,hdmi_port,usb_port,value_score
0,1,tcl,1,0,42999,4.65,medium,55.0,qled,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,16.0,58.0,flipkart,1,2.0,0.006272
1,2,lg,1,0,41999,4.55,medium,55.0,led,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,19.2,55.0,flipkart,1,1.0,0.005958
2,3,xiaomi,1,0,36999,4.35,medium,55.0,qled,3851.029614,3840.0,2160.0,1,34.0,medium,2.0,32.0,55.0,amazon,1,2.0,0.006466
3,4,lg,1,0,30999,4.40,high,43.0,led,3854.102013,3840.0,2160.0,1,20.0,slow,2.0,19.2,52.0,flipkart,1,1.0,0.007381
4,5,philips,1,0,74999,4.05,medium,75.0,qled,3848.091475,3840.0,2160.0,1,30.0,slow,2.0,32.0,67.0,amazon,1,2.0,0.003618

In [126]:
df1['smart_features'] = (df1['wifi'] + df1['usb_port'] + df1['hdmi_port'])

In [127]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,size_category,inches,display_type,ppi,resolution_width,resolution_height,wifi,fast_charging,charging_category,ram,rom,Spec_Score,Company,hdmi_port,usb_port,value_score,smart_features
0,1,tcl,1,0,42999,4.65,medium,55.0,qled,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,16.0,58.0,flipkart,1,2.0,0.006272,4.0
1,2,lg,1,0,41999,4.55,medium,55.0,led,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,19.2,55.0,flipkart,1,1.0,0.005958,3.0
2,3,xiaomi,1,0,36999,4.35,medium,55.0,qled,3851.029614,3840.0,2160.0,1,34.0,medium,2.0,32.0,55.0,amazon,1,2.0,0.006466,4.0
3,4,lg,1,0,30999,4.40,high,43.0,led,3854.102013,3840.0,2160.0,1,20.0,slow,2.0,19.2,52.0,flipkart,1,1.0,0.007381,3.0
4,5,philips,1,0,74999,4.05,medium,75.0,qled,3848.091475,3840.0,2160.0,1,30.0,slow,2.0,32.0,67.0,amazon,1,2.0,0.003618,4.0

In [128]:
ohe_col = ['Company']

In [129]:
from sklearn.preprocessing import OneHotEncoder

In [130]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
x_one = ohe.fit_transform(df1[ohe_col])

In [131]:
ohe_df = pd.DataFrame(x_one, columns=ohe.get_feature_names_out(ohe_col), index=df1.index)

In [132]:
ohe_df.head()

   Company_amazon  Company_croma  Company_flipkart
0             0.0            0.0               1.0
1             0.0            0.0               1.0
2             1.0            0.0               0.0
3             0.0            0.0               1.0
4             1.0            0.0               0.0

In [133]:
df1 = pd.concat([df1.drop(columns = ['Company']), ohe_df], axis=1)

In [134]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,size_category,inches,display_type,ppi,resolution_width,resolution_height,wifi,fast_charging,charging_category,ram,rom,Spec_Score,hdmi_port,usb_port,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart
0,1,tcl,1,0,42999,4.65,medium,55.0,qled,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,16.0,58.0,1,2.0,0.006272,4.0,0.0,0.0,1.0
1,2,lg,1,0,41999,4.55,medium,55.0,led,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,19.2,55.0,1,1.0,0.005958,3.0,0.0,0.0,1.0
2,3,xiaomi,1,0,36999,4.35,medium,55.0,qled,3851.029614,3840.0,2160.0,1,34.0,medium,2.0,32.0,55.0,1,2.0,0.006466,4.0,1.0,0.0,0.0
3,4,lg,1,0,30999,4.40,high,43.0,led,3854.102013,3840.0,2160.0,1,20.0,slow,2.0,19.2,52.0,1,1.0,0.007381,3.0,0.0,0.0,1.0
4,5,philips,1,0,74999,4.05,medium,75.0,qled,3848.091475,3840.0,2160.0,1,30.0,slow,2.0,32.0,67.0,1,2.0,0.003618,4.0,1.0,0.0,0.0

In [135]:
df1.isnull().sum()

index                0
brand                0
ultra_hd             0
full_hd              0
Price                0
Rating               0
size_category        0
inches               0
display_type         0
ppi                  0
resolution_width     0
resolution_height    0
wifi                 0
fast_charging        0
charging_category    0
ram                  0
rom                  0
Spec_Score           0
hdmi_port            0
usb_port             0
value_score          0
smart_features       0
Company_amazon       0
Company_croma        0
Company_flipkart     0
dtype: int64

In [136]:
df1['brand'].value_counts()

brand
samsung         171
tcl              94
lg               94
hisense          48
sony             47
xiaomi           35
haier            34
realme           32
croma            31
toshiba          26
blaupunkt        24
thomson          22
motorola         22
acer             21
onida            20
foxsky           18
vw               17
vu               17
sansui           17
kodak            16
coocaa           14
philips          14
wobble           13
panasonic        13
iffalcon         12
uniboom          10
reliance         10
infinix           8
acerpure          8
lumio             7
metz              7
beston            7
innoq             6
lloyd             5
bush              5
rgl               5
nu                5
bpl               5
vzy               5
marq              4
nacson            3
ifflacon          3
kenstar           3
blackdecker       3
tseries           3
compaq            2
akai              2
elista            2
skylive           2
kodal             1
aiwa              1
hyundai           1
westinghouse      1
beethosol         1
xelectron         1
redmi             1
bazeegar          1
Name: count, dtype: int64

In [137]:
brand_score = {
    'samsung': 10,
    'lg': 10,
    'sony': 10,
    'tcl': 8,
    'hisense': 8,
    'xiaomi': 8,
    'panasonic': 8,
    'toshiba': 8,
    'philips': 8,
    'realme': 7,
    'acer': 7,
    'motorola': 7,
    'haier': 7,
    'vu': 7,
    'thomson': 7,
    'iffalcon': 7,
    'redmi': 7,
    'kodak': 6,
    'onida': 6,
    'croma': 6,
    'infinix': 6,
    'blaupunkt': 6,
    'acerpure': 5,
    'lloyd': 5,
    'sansui': 5,
    'reliance': 5,
    'marq': 5,
    'coocaa': 5,
    'foxsky': 4,
    'wobble': 4,
    'uniboom': 4,
    'beston': 4,
    'innoq': 3,
    'bush': 3,
    'bpl': 3,
    'aiwa': 3,
    'hyundai': 3,
    'blackdecker': 3,
    'tseries': 3,
    'compaq': 3,
    'akai': 3,
    'elista': 3,
    'skylive': 2,
    'vzy': 2,
    'nu': 2,
    'rgl': 2,
    'metz': 2,
    'nacson': 2,
    'bazeegar': 1,
    'xelectron': 1,
    'beethosol': 1,
    'westinghouse': 1,
    'kodal': 1
}

df1['brand_score'] = df1['brand'].map(brand_score)

In [138]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,size_category,inches,display_type,ppi,resolution_width,resolution_height,wifi,fast_charging,charging_category,ram,rom,Spec_Score,hdmi_port,usb_port,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart,brand_score
0,1,tcl,1,0,42999,4.65,medium,55.0,qled,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,16.0,58.0,1,2.0,0.006272,4.0,0.0,0.0,1.0,8.0
1,2,lg,1,0,41999,4.55,medium,55.0,led,3851.029614,3840.0,2160.0,1,20.0,slow,2.0,19.2,55.0,1,1.0,0.005958,3.0,0.0,0.0,1.0,10.0
2,3,xiaomi,1,0,36999,4.35,medium,55.0,qled,3851.029614,3840.0,2160.0,1,34.0,medium,2.0,32.0,55.0,1,2.0,0.006466,4.0,1.0,0.0,0.0,8.0
3,4,lg,1,0,30999,4.40,high,43.0,led,3854.102013,3840.0,2160.0,1,20.0,slow,2.0,19.2,52.0,1,1.0,0.007381,3.0,0.0,0.0,1.0,10.0
4,5,philips,1,0,74999,4.05,medium,75.0,qled,3848.091475,3840.0,2160.0,1,30.0,slow,2.0,32.0,67.0,1,2.0,0.003618,4.0,1.0,0.0,0.0,8.0

In [139]:
bins = ['ppi', 'resolution_width', 'resolution_height', 'fast_charging', 'ram', 'usb_port', 'Spec_Score']

In [140]:
from sklearn.preprocessing import KBinsDiscretizer

In [141]:
kbins = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='quantile')
kbin = kbins.fit_transform(df1[bins])

C:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_discretization.py:279: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  warnings.warn(
C:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_discretization.py:279: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  warnings.warn(
C:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_discretization.py:279: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn(
C:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_discretization.py:279: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 4 are removed. Consider decreasing the number of bins.
  warnings.warn(
C:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_discretization.py:279: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  warnings.warn(

In [142]:
kbin_df = pd.DataFrame(kbin,
                      columns = bins,
                      index=df1.index)

In [143]:
df1 = pd.concat(
    [df1.drop(columns=bins), kbin_df],
    axis=1
)

In [144]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,size_category,inches,display_type,wifi,charging_category,rom,hdmi_port,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart,brand_score,ppi,resolution_width,resolution_height,fast_charging,ram,usb_port,Spec_Score
0,1,tcl,1,0,42999,4.65,medium,55.0,qled,1,slow,16.0,1,0.006272,4.0,0.0,0.0,1.0,8.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0
1,2,lg,1,0,41999,4.55,medium,55.0,led,1,slow,19.2,1,0.005958,3.0,0.0,0.0,1.0,10.0,3.0,1.0,2.0,1.0,1.0,0.0,2.0
2,3,xiaomi,1,0,36999,4.35,medium,55.0,qled,1,medium,32.0,1,0.006466,4.0,1.0,0.0,0.0,8.0,3.0,1.0,2.0,2.0,1.0,1.0,2.0
3,4,lg,1,0,30999,4.40,high,43.0,led,1,slow,19.2,1,0.007381,3.0,0.0,0.0,1.0,10.0,4.0,1.0,2.0,1.0,1.0,0.0,2.0
4,5,philips,1,0,74999,4.05,medium,75.0,qled,1,slow,32.0,1,0.003618,4.0,1.0,0.0,0.0,8.0,1.0,1.0,2.0,2.0,1.0,1.0,4.0

In [145]:
ord_col = ['size_category', 'charging_category']

In [146]:
from sklearn.preprocessing import OrdinalEncoder

In [149]:
orde = OrdinalEncoder(categories='auto', handle_unknown='error')
ord_train = orde.fit_transform(df1[ord_col])

In [150]:
ord_df = pd.DataFrame(ord_train,
                     columns=ord_col,
                     index=df1.index)

In [151]:
ord_df.head()

   size_category  charging_category
0            1.0                2.0
1            1.0                2.0
2            1.0                1.0
3            0.0                2.0
4            1.0                2.0

In [152]:
df1 = pd.concat([df1.drop(columns = ord_col), ord_df], axis=1)

In [153]:
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,wifi,rom,hdmi_port,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart,brand_score,ppi,resolution_width,resolution_height,fast_charging,ram,usb_port,Spec_Score,size_category,charging_category
0,1,tcl,1,0,42999,4.65,55.0,qled,1,16.0,1,0.006272,4.0,0.0,0.0,1.0,8.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0
1,2,lg,1,0,41999,4.55,55.0,led,1,19.2,1,0.005958,3.0,0.0,0.0,1.0,10.0,3.0,1.0,2.0,1.0,1.0,0.0,2.0,1.0,2.0
2,3,xiaomi,1,0,36999,4.35,55.0,qled,1,32.0,1,0.006466,4.0,1.0,0.0,0.0,8.0,3.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0
3,4,lg,1,0,30999,4.40,43.0,led,1,19.2,1,0.007381,3.0,0.0,0.0,1.0,10.0,4.0,1.0,2.0,1.0,1.0,0.0,2.0,0.0,2.0
4,5,philips,1,0,74999,4.05,75.0,qled,1,32.0,1,0.003618,4.0,1.0,0.0,0.0,8.0,1.0,1.0,2.0,2.0,1.0,1.0,4.0,1.0,2.0

In [156]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   int64
 3   full_hd            1000 non-null   int64
 4   Price              1000 non-null   int64
 5   Rating             1000 non-null   float64
 6   inches             1000 non-null   float64
 7   display_type       1000 non-null   object
 8   wifi               1000 non-null   int64
 9   rom                1000 non-null   float64
 10  hdmi_port          1000 non-null   int64
 11  value_score        1000 non-null   float64
 12  smart_features     1000 non-null   float64
 13  Company_amazon     1000 non-null   float64
 14  Company_croma      1000 non-null   float64
 15  Company_flipkart   1000 non-null   float64
 16  brand_score        970 non-null    float64
 17  ppi                1000 non-null   float64
 18  resolution_width   1000 non-null   float64
 19  resolution_height  1000 non-null   float64
 20  fast_charging      1000 non-null   float64
 21  ram                1000 non-null   float64
 22  usb_port           1000 non-null   float64
 23  Spec_Score         1000 non-null   float64
 24  size_category      1000 non-null   float64
 25  charging_category  1000 non-null   float64
dtypes: float64(18), int64(6), object(2)
memory usage: 203.2+ KB

In [154]:
df1.to_csv('feature_engineering_tv.csv')