In [86]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as plt

In [87]:
tv_data = pd.read_csv('television_outlier_detection.csv')
rs_data = pd.read_csv('rs.csv')

In [88]:
tv_data.head()

,Unnamed: 0,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,wifi,rom,hdmi_port,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart,ppi,resolution_width,resolution_height,fast_charging,ram,usb_port,Spec_Score,size_category,charging_category,brand_score
0,0,1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0
1,1,2,lg,1,0,10.645425,4.55,55.0,led,1,19.2,1,0.005958,3.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,0.0,2.0,1.0,2.0,10.0
2,2,3,xiaomi,1,0,10.518673,4.35,55.0,qled,1,32.0,1,0.006466,4.0,1.0,0.0,0.0,3.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,8.0
3,3,4,lg,1,0,10.341742,4.40,43.0,led,1,19.2,1,0.007381,3.0,0.0,0.0,1.0,4.0,1.0,2.0,1.0,1.0,0.0,2.0,0.0,2.0,10.0
4,4,5,philips,1,0,11.225243,4.05,75.0,qled,1,32.0,1,0.003618,4.0,1.0,0.0,0.0,1.0,1.0,2.0,2.0,1.0,1.0,4.0,1.0,2.0,8.0

In [89]:
rs_data.head()

,Unnamed: 0,Model,url
0,0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),https://cdn1.smartprix.com/rx-igjcIcyXT-w280-h...
1,1,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,https://cdn1.smartprix.com/rx-iAV6QAzcH-w280-h...
2,2,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,https://cdn1.smartprix.com/rx-iUmLQrhUR-w280-h...
3,3,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,https://cdn1.smartprix.com/rx-iD6UNJXDf-w280-h...
4,4,Philips Lumina Series 75 inch Ultra HD 4K Smar...,https://cdn1.smartprix.com/rx-iwmYKVnuL-w280-h...

In [90]:
first_data = pd.read_csv('Televisions.csv')
first_data.head()

,Model,Price,Rating,Specs,Company,Spec_Score
0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999",4.65,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,"₹41,999",4.55,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,"₹36,999",4.35,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,"₹30,999",4.40,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,Philips Lumina Series 75 inch Ultra HD 4K Smar...,"₹74,999",4.05,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [91]:
tv_data = tv_data.drop(columns = ['Unnamed: 0'])
rs_data = rs_data.drop(columns = ['Unnamed: 0'])

In [92]:
tv_data.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,wifi,rom,hdmi_port,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart,ppi,resolution_width,resolution_height,fast_charging,ram,usb_port,Spec_Score,size_category,charging_category,brand_score
0,1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0
1,2,lg,1,0,10.645425,4.55,55.0,led,1,19.2,1,0.005958,3.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,0.0,2.0,1.0,2.0,10.0
2,3,xiaomi,1,0,10.518673,4.35,55.0,qled,1,32.0,1,0.006466,4.0,1.0,0.0,0.0,3.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,8.0
3,4,lg,1,0,10.341742,4.40,43.0,led,1,19.2,1,0.007381,3.0,0.0,0.0,1.0,4.0,1.0,2.0,1.0,1.0,0.0,2.0,0.0,2.0,10.0
4,5,philips,1,0,11.225243,4.05,75.0,qled,1,32.0,1,0.003618,4.0,1.0,0.0,0.0,1.0,1.0,2.0,2.0,1.0,1.0,4.0,1.0,2.0,8.0

In [93]:
rs_data.head()

,Model,url
0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),https://cdn1.smartprix.com/rx-igjcIcyXT-w280-h...
1,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,https://cdn1.smartprix.com/rx-iAV6QAzcH-w280-h...
2,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,https://cdn1.smartprix.com/rx-iUmLQrhUR-w280-h...
3,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,https://cdn1.smartprix.com/rx-iD6UNJXDf-w280-h...
4,Philips Lumina Series 75 inch Ultra HD 4K Smar...,https://cdn1.smartprix.com/rx-iwmYKVnuL-w280-h...

In [94]:
total_df = tv_data.merge(first_data, on='Rating', how='left')

In [95]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
total_df.head()

,index,brand,ultra_hd,full_hd,Price_x,Rating,inches,display_type,wifi,rom,hdmi_port,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart,ppi,resolution_width,resolution_height,fast_charging,ram,usb_port,Spec_Score_x,size_category,charging_category,brand_score,Model,Price_y,Specs,Company,Spec_Score_y
0,1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999","55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,Xiaomi TV FX Series 2026 55 inch Ultra HD 4K S...,"₹44,999","55 in, Mini LED TV4K Resolution, 3840 x 2160 p...",amazon,61.0
2,1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,TCL S5500 32 inch Full HD Smart LED TV (32S5500),"₹10,999","32 in, LED TVFull HD, 1920 x 1080 pixelsWifi, ...",flipkart,37.0
3,1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,Hisense Q6N 55 inch Ultra HD 4K Smart QLED TV ...,"₹31,299","55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",croma,66.0
4,1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,Realme TechLife 32 inch HD Ready Smart QLED TV...,"₹11,199","32 in, QLED TV1366 x 768 pixelsWifi, EthernetS...",flipkart,43.0

In [96]:
total_df.columns

Index(['index', 'brand', 'ultra_hd', 'full_hd', 'Price_x', 'Rating', 'inches',
       'display_type', 'wifi', 'rom', 'hdmi_port', 'value_score',
       'smart_features', 'Company_amazon', 'Company_croma', 'Company_flipkart',
       'ppi', 'resolution_width', 'resolution_height', 'fast_charging', 'ram',
       'usb_port', 'Spec_Score_x', 'size_category', 'charging_category',
       'brand_score', 'Model', 'Price_y', 'Specs', 'Company', 'Spec_Score_y'],
      dtype='object')

In [97]:
df = total_df.drop(columns=['index', 'Company_amazon', 'Company_croma', 'Company_flipkart'])
df.head()

,brand,ultra_hd,full_hd,Price_x,Rating,inches,display_type,wifi,rom,hdmi_port,value_score,smart_features,ppi,resolution_width,resolution_height,fast_charging,ram,usb_port,Spec_Score_x,size_category,charging_category,brand_score,Model,Price_y,Specs,Company,Spec_Score_y
0,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999","55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,Xiaomi TV FX Series 2026 55 inch Ultra HD 4K S...,"₹44,999","55 in, Mini LED TV4K Resolution, 3840 x 2160 p...",amazon,61.0
2,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,TCL S5500 32 inch Full HD Smart LED TV (32S5500),"₹10,999","32 in, LED TVFull HD, 1920 x 1080 pixelsWifi, ...",flipkart,37.0
3,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,Hisense Q6N 55 inch Ultra HD 4K Smart QLED TV ...,"₹31,299","55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",croma,66.0
4,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,Realme TechLife 32 inch HD Ready Smart QLED TV...,"₹11,199","32 in, QLED TV1366 x 768 pixelsWifi, EthernetS...",flipkart,43.0

In [98]:
cols = [
    'ultra_hd',
    'full_hd',
#     'Price',
#     'Rating',
    'inches',
    'display_type',
    'wifi',
    'rom',
    'hdmi_port',
    'value_score',
    'smart_features',
    'ppi',
    'resolution_width',
    'resolution_height',
    'fast_charging',
    'ram',
    'usb_port',
#     'Spec_Score',
    'size_category',
    'charging_category',
    'brand_score'
]

In [99]:
df['tags'] = df[cols].astype(str).agg(' '.join, axis=1)

In [100]:
df.head()

,brand,ultra_hd,full_hd,Price_x,Rating,inches,display_type,wifi,rom,hdmi_port,value_score,smart_features,ppi,resolution_width,resolution_height,fast_charging,ram,usb_port,Spec_Score_x,size_category,charging_category,brand_score,Model,Price_y,Specs,Company,Spec_Score_y,tags
0,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999","55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...
1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,Xiaomi TV FX Series 2026 55 inch Ultra HD 4K S...,"₹44,999","55 in, Mini LED TV4K Resolution, 3840 x 2160 p...",amazon,61.0,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...
2,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,TCL S5500 32 inch Full HD Smart LED TV (32S5500),"₹10,999","32 in, LED TVFull HD, 1920 x 1080 pixelsWifi, ...",flipkart,37.0,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...
3,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,Hisense Q6N 55 inch Ultra HD 4K Smart QLED TV ...,"₹31,299","55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",croma,66.0,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...
4,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,1,0.006272,4.0,3.0,1.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,8.0,Realme TechLife 32 inch HD Ready Smart QLED TV...,"₹11,199","32 in, QLED TV1366 x 768 pixelsWifi, EthernetS...",flipkart,43.0,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...

In [101]:
new_df = df[['Model', 'tags', 'Price_y', 'Rating', 'Spec_Score_y']]

In [102]:
new_df.head()

,Model,tags,Price_y,Rating,Spec_Score_y
0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹42,999",4.65,58.0
1,Xiaomi TV FX Series 2026 55 inch Ultra HD 4K S...,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹44,999",4.65,61.0
2,TCL S5500 32 inch Full HD Smart LED TV (32S5500),1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹10,999",4.65,37.0
3,Hisense Q6N 55 inch Ultra HD 4K Smart QLED TV ...,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹31,299",4.65,66.0
4,Realme TechLife 32 inch HD Ready Smart QLED TV...,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹11,199",4.65,43.0

In [103]:
final_data = new_df.merge(rs_data, on='Model', how = 'left')

In [104]:
final_data.head()

,Model,tags,Price_y,Rating,Spec_Score_y,url
0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹42,999",4.65,58.0,https://cdn1.smartprix.com/rx-igjcIcyXT-w280-h...
1,Xiaomi TV FX Series 2026 55 inch Ultra HD 4K S...,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹44,999",4.65,61.0,https://cdn1.smartprix.com/rx-iEZL67XoU-w280-h...
2,TCL S5500 32 inch Full HD Smart LED TV (32S5500),1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹10,999",4.65,37.0,https://cdn1.smartprix.com/rx-ieSgAzuaX-w280-h...
3,Hisense Q6N 55 inch Ultra HD 4K Smart QLED TV ...,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹31,299",4.65,66.0,https://cdn1.smartprix.com/rx-iHZOcriUa-w280-h...
4,Realme TechLife 32 inch HD Ready Smart QLED TV...,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,"₹11,199",4.65,43.0,https://cdn1.smartprix.com/rx-i2F37F58h-w280-h...

In [105]:
final_data['Price_y'] = final_data['Price_y'].str.replace('₹', '').str.replace(',', '')

In [106]:
final_data.head()

,Model,tags,Price_y,Rating,Spec_Score_y,url
0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,42999,4.65,58.0,https://cdn1.smartprix.com/rx-igjcIcyXT-w280-h...
1,Xiaomi TV FX Series 2026 55 inch Ultra HD 4K S...,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,44999,4.65,61.0,https://cdn1.smartprix.com/rx-iEZL67XoU-w280-h...
2,TCL S5500 32 inch Full HD Smart LED TV (32S5500),1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,10999,4.65,37.0,https://cdn1.smartprix.com/rx-ieSgAzuaX-w280-h...
3,Hisense Q6N 55 inch Ultra HD 4K Smart QLED TV ...,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,31299,4.65,66.0,https://cdn1.smartprix.com/rx-iHZOcriUa-w280-h...
4,Realme TechLife 32 inch HD Ready Smart QLED TV...,1 0 55.0 qled 1 16.0 1 0.0062722388892764 4.0 ...,11199,4.65,43.0,https://cdn1.smartprix.com/rx-i2F37F58h-w280-h...

In [107]:
from sklearn.feature_extraction.text import CountVectorizer

In [108]:
cv = CountVectorizer()

In [109]:
vectors = cv.fit_transform(final_data['tags']).toarray()

In [110]:
vectors.shape

(63352, 930)

In [111]:
from sklearn.metrics.pairwise import cosine_similarity

In [112]:
def recommend(name):
    index = final_data[final_data['Model'] == name].index[0]

    similarity = cosine_similarity(
        vectors[index:index+1],
        vectors
    ).flatten()

    distances = sorted(
        list(enumerate(similarity)),
        reverse=True,
        key=lambda x: x[1]
    )

    for i in distances[1:6]:
        print(final_data.iloc[i[0]]['Model'])
        print(final_data.iloc[i[0]]['Price_y'])

In [113]:
recommend('TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K)')

Xiaomi TV FX Series 2026 55 inch Ultra HD 4K Smart QD-Mini LED TV (L55MC-FSMIN)
44999
TCL S5500 32 inch Full HD Smart LED TV (32S5500)
10999
Hisense Q6N 55 inch Ultra HD 4K Smart QLED TV (55Q6N)
31299
Realme TechLife 32 inch HD Ready Smart QLED TV (32HDGQRASOQ)
11199
Samsung M71H 43 inch Ultra HD 4K Smart Mini LED TV (UA43M71HAULXL)
44690

In [114]:
import pickle

pickle.dump(final_data,open('final_data.pkl', 'wb'))
pickle.dump(vectors,open('vectors.pkl', 'wb'))