In [310]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re

In [311]:
df = pd.read_csv('cleaned_data.csv')
df.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,rom,hdmi_port,Company,Spec_Score,usb_port
0,1,tcl,True,False,42999,4.65,55,qled,3840.0,2160.0,True,20.0,2.0,16.0,True,flipkart,58.0,2.0
1,2,lg,True,False,41999,4.55,55,led,3840.0,2160.0,True,20.0,2.0,NaN,True,flipkart,55.0,1.0
2,3,xiaomi,True,False,36999,4.35,55,qled,3840.0,2160.0,True,34.0,2.0,32.0,True,amazon,55.0,2.0
3,4,lg,True,False,30999,4.40,43,led,3840.0,2160.0,True,20.0,2.0,NaN,True,flipkart,52.0,1.0
4,5,philips,True,False,74999,4.05,75,qled,3840.0,2160.0,True,30.0,2.0,32.0,True,amazon,67.0,2.0

In [312]:
df1 = df.copy()
df1.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,rom,hdmi_port,Company,Spec_Score,usb_port
0,1,tcl,True,False,42999,4.65,55,qled,3840.0,2160.0,True,20.0,2.0,16.0,True,flipkart,58.0,2.0
1,2,lg,True,False,41999,4.55,55,led,3840.0,2160.0,True,20.0,2.0,NaN,True,flipkart,55.0,1.0
2,3,xiaomi,True,False,36999,4.35,55,qled,3840.0,2160.0,True,34.0,2.0,32.0,True,amazon,55.0,2.0
3,4,lg,True,False,30999,4.40,43,led,3840.0,2160.0,True,20.0,2.0,NaN,True,flipkart,52.0,1.0
4,5,philips,True,False,74999,4.05,75,qled,3840.0,2160.0,True,30.0,2.0,32.0,True,amazon,67.0,2.0

In [313]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   bool
 3   full_hd            1000 non-null   bool
 4   Price              1000 non-null   int64
 5   Rating             1000 non-null   float64
 6   inches             999 non-null    object
 7   display_type       997 non-null    object
 8   resolution_width   840 non-null    float64
 9   resolution_height  997 non-null    float64
 10  wifi               1000 non-null   bool
 11  fast_charging      990 non-null    float64
 12  ram                443 non-null    float64
 13  rom                352 non-null    float64
 14  hdmi_port          1000 non-null   bool
 15  Company            1000 non-null   object
 16  Spec_Score         998 non-null    float64
 17  usb_port           986 non-null    float64
dtypes: bool(4), float64(8), int64(2), object(4)
memory usage: 113.4+ KB

In [314]:
df1['resolution_width'] = df1['resolution_width'].astype(float)

In [315]:
numeric_cols = ['resolution_width', 'resolution_height', 'fast_charging', 'ram', 'rom', 'Spec_Score', 'usb_port']

In [316]:
from sklearn.impute import KNNImputer

In [317]:
knn = KNNImputer(n_neighbors=5)
knn_impute = knn.fit_transform(df1[numeric_cols])

In [318]:
imputed_df = pd.DataFrame(knn_impute,
                         columns=numeric_cols,
                         index=df1.index)

In [319]:
imputed_df.isnull().sum()

resolution_width     0
resolution_height    0
fast_charging        0
ram                  0
rom                  0
Spec_Score           0
usb_port             0
dtype: int64

In [320]:
df2 = pd.concat([df1.drop(columns = numeric_cols), imputed_df], axis=1)

In [321]:
df2.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,wifi,hdmi_port,Company,resolution_width,resolution_height,fast_charging,ram,rom,Spec_Score,usb_port
0,1,tcl,True,False,42999,4.65,55,qled,True,True,flipkart,3840.0,2160.0,20.0,2.0,16.0,58.0,2.0
1,2,lg,True,False,41999,4.55,55,led,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,55.0,1.0
2,3,xiaomi,True,False,36999,4.35,55,qled,True,True,amazon,3840.0,2160.0,34.0,2.0,32.0,55.0,2.0
3,4,lg,True,False,30999,4.40,43,led,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,52.0,1.0
4,5,philips,True,False,74999,4.05,75,qled,True,True,amazon,3840.0,2160.0,30.0,2.0,32.0,67.0,2.0

In [322]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   bool
 3   full_hd            1000 non-null   bool
 4   Price              1000 non-null   int64
 5   Rating             1000 non-null   float64
 6   inches             999 non-null    object
 7   display_type       997 non-null    object
 8   wifi               1000 non-null   bool
 9   hdmi_port          1000 non-null   bool
 10  Company            1000 non-null   object
 11  resolution_width   1000 non-null   float64
 12  resolution_height  1000 non-null   float64
 13  fast_charging      1000 non-null   float64
 14  ram                1000 non-null   float64
 15  rom                1000 non-null   float64
 16  Spec_Score         1000 non-null   float64
 17  usb_port           1000 non-null   float64
dtypes: bool(4), float64(8), int64(2), object(4)
memory usage: 113.4+ KB

In [323]:
cat_col = ['inches', 'display_type']

In [324]:
from sklearn.impute import SimpleImputer

In [325]:
simple = SimpleImputer(strategy = 'most_frequent')
si_imputer = simple.fit_transform(df1[cat_col])

In [326]:
si_df = pd.DataFrame(si_imputer,
                    columns = cat_col,
                    index=df1.index)

In [327]:
si_df.isnull().sum()

inches          0
display_type    0
dtype: int64

In [328]:
df2 = pd.concat([df2.drop(columns = cat_col), si_df], axis=1)

In [329]:
df2.head()

,index,brand,ultra_hd,full_hd,Price,Rating,wifi,hdmi_port,Company,resolution_width,resolution_height,fast_charging,ram,rom,Spec_Score,usb_port,inches,display_type
0,1,tcl,True,False,42999,4.65,True,True,flipkart,3840.0,2160.0,20.0,2.0,16.0,58.0,2.0,55,qled
1,2,lg,True,False,41999,4.55,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,55.0,1.0,55,led
2,3,xiaomi,True,False,36999,4.35,True,True,amazon,3840.0,2160.0,34.0,2.0,32.0,55.0,2.0,55,qled
3,4,lg,True,False,30999,4.40,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,52.0,1.0,43,led
4,5,philips,True,False,74999,4.05,True,True,amazon,3840.0,2160.0,30.0,2.0,32.0,67.0,2.0,75,qled

In [330]:
df2['inches']

0      55
1      55
2      55
3      43
4      75
       ..
995    24
996    43
997    75
998    50
999    40
Name: inches, Length: 1000, dtype: object

In [331]:
col = df2.pop('inches')
df2.insert(6, 'inches', col)

In [332]:
df2.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,wifi,hdmi_port,Company,resolution_width,resolution_height,fast_charging,ram,rom,Spec_Score,usb_port,display_type
0,1,tcl,True,False,42999,4.65,55,True,True,flipkart,3840.0,2160.0,20.0,2.0,16.0,58.0,2.0,qled
1,2,lg,True,False,41999,4.55,55,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,55.0,1.0,led
2,3,xiaomi,True,False,36999,4.35,55,True,True,amazon,3840.0,2160.0,34.0,2.0,32.0,55.0,2.0,qled
3,4,lg,True,False,30999,4.40,43,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,52.0,1.0,led
4,5,philips,True,False,74999,4.05,75,True,True,amazon,3840.0,2160.0,30.0,2.0,32.0,67.0,2.0,qled

In [333]:
col = df2.pop('display_type')
df2.insert(7, 'display_type', col)

In [334]:
df2.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,wifi,hdmi_port,Company,resolution_width,resolution_height,fast_charging,ram,rom,Spec_Score,usb_port
0,1,tcl,True,False,42999,4.65,55,qled,True,True,flipkart,3840.0,2160.0,20.0,2.0,16.0,58.0,2.0
1,2,lg,True,False,41999,4.55,55,led,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,55.0,1.0
2,3,xiaomi,True,False,36999,4.35,55,qled,True,True,amazon,3840.0,2160.0,34.0,2.0,32.0,55.0,2.0
3,4,lg,True,False,30999,4.40,43,led,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,52.0,1.0
4,5,philips,True,False,74999,4.05,75,qled,True,True,amazon,3840.0,2160.0,30.0,2.0,32.0,67.0,2.0

In [335]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   bool
 3   full_hd            1000 non-null   bool
 4   Price              1000 non-null   int64
 5   Rating             1000 non-null   float64
 6   inches             1000 non-null   object
 7   display_type       1000 non-null   object
 8   wifi               1000 non-null   bool
 9   hdmi_port          1000 non-null   bool
 10  Company            1000 non-null   object
 11  resolution_width   1000 non-null   float64
 12  resolution_height  1000 non-null   float64
 13  fast_charging      1000 non-null   float64
 14  ram                1000 non-null   float64
 15  rom                1000 non-null   float64
 16  Spec_Score         1000 non-null   float64
 17  usb_port           1000 non-null   float64
dtypes: bool(4), float64(8), int64(2), object(4)
memory usage: 113.4+ KB

In [336]:
df2['inches'].value_counts()

inches
55           219
43           195
65           164
32           146
75            93
50            81
85            24
40            23
24            15
77             8
98             7
100            6
86             3
48             3
31.5           2
23.62          1
120            1
54.72          1
39.37          1
Supported      1
49             1
31.89          1
115            1
83             1
42.52          1
58             1
Name: count, dtype: int64

In [337]:
df2['inches'] = df2['inches'].str.replace('Supported', '55')

In [338]:
df2['inches'].value_counts()

inches
55       220
43       195
65       164
32       146
75        93
50        81
85        24
40        23
24        15
77         8
98         7
100        6
48         3
86         3
31.5       2
120        1
23.62      1
54.72      1
39.37      1
42.52      1
31.89      1
115        1
83         1
49         1
58         1
Name: count, dtype: int64

In [339]:
df2['inches'] = df2['inches'].astype(float)

In [340]:
df2['inches'].value_counts()

inches
55.00     220
43.00     195
65.00     164
32.00     146
75.00      93
50.00      81
85.00      24
40.00      23
24.00      15
77.00       8
98.00       7
100.00      6
48.00       3
86.00       3
31.50       2
120.00      1
23.62       1
54.72       1
39.37       1
42.52       1
31.89       1
115.00      1
83.00       1
49.00       1
58.00       1
Name: count, dtype: int64

In [341]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   bool
 3   full_hd            1000 non-null   bool
 4   Price              1000 non-null   int64
 5   Rating             1000 non-null   float64
 6   inches             1000 non-null   float64
 7   display_type       1000 non-null   object
 8   wifi               1000 non-null   bool
 9   hdmi_port          1000 non-null   bool
 10  Company            1000 non-null   object
 11  resolution_width   1000 non-null   float64
 12  resolution_height  1000 non-null   float64
 13  fast_charging      1000 non-null   float64
 14  ram                1000 non-null   float64
 15  rom                1000 non-null   float64
 16  Spec_Score         1000 non-null   float64
 17  usb_port           1000 non-null   float64
dtypes: bool(4), float64(9), int64(2), object(3)
memory usage: 113.4+ KB

In [342]:
df2.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,wifi,hdmi_port,Company,resolution_width,resolution_height,fast_charging,ram,rom,Spec_Score,usb_port
0,1,tcl,True,False,42999,4.65,55.0,qled,True,True,flipkart,3840.0,2160.0,20.0,2.0,16.0,58.0,2.0
1,2,lg,True,False,41999,4.55,55.0,led,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,55.0,1.0
2,3,xiaomi,True,False,36999,4.35,55.0,qled,True,True,amazon,3840.0,2160.0,34.0,2.0,32.0,55.0,2.0
3,4,lg,True,False,30999,4.40,43.0,led,True,True,flipkart,3840.0,2160.0,20.0,2.0,19.2,52.0,1.0
4,5,philips,True,False,74999,4.05,75.0,qled,True,True,amazon,3840.0,2160.0,30.0,2.0,32.0,67.0,2.0

In [343]:
col = df2.pop('wifi')
df2.insert(12, 'wifi', col)

In [344]:
col = df2.pop('hdmi_port')
df2.insert(15, 'hdmi_port', col)

In [346]:
col = df2.pop('Company')
df2.insert(16, 'Company', col)

In [347]:
df2.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,rom,hdmi_port,Spec_Score,Company,usb_port
0,1,tcl,True,False,42999,4.65,55.0,qled,3840.0,2160.0,True,20.0,2.0,16.0,True,58.0,flipkart,2.0
1,2,lg,True,False,41999,4.55,55.0,led,3840.0,2160.0,True,20.0,2.0,19.2,True,55.0,flipkart,1.0
2,3,xiaomi,True,False,36999,4.35,55.0,qled,3840.0,2160.0,True,34.0,2.0,32.0,True,55.0,amazon,2.0
3,4,lg,True,False,30999,4.40,43.0,led,3840.0,2160.0,True,20.0,2.0,19.2,True,52.0,flipkart,1.0
4,5,philips,True,False,74999,4.05,75.0,qled,3840.0,2160.0,True,30.0,2.0,32.0,True,67.0,amazon,2.0

In [349]:
df2['ultra_hd'] = df2['ultra_hd'].astype(int)

In [351]:
df2['ultra_hd'].value_counts()

ultra_hd
1    757
0    243
Name: count, dtype: int64

In [352]:
df2['full_hd'] = df2['full_hd'].astype(int)
df2['wifi'] = df2['wifi'].astype(int)
df2['hdmi_port'] = df2['hdmi_port'].astype(int)

In [353]:
df2.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,rom,hdmi_port,Spec_Score,Company,usb_port
0,1,tcl,1,0,42999,4.65,55.0,qled,3840.0,2160.0,1,20.0,2.0,16.0,1,58.0,flipkart,2.0
1,2,lg,1,0,41999,4.55,55.0,led,3840.0,2160.0,1,20.0,2.0,19.2,1,55.0,flipkart,1.0
2,3,xiaomi,1,0,36999,4.35,55.0,qled,3840.0,2160.0,1,34.0,2.0,32.0,1,55.0,amazon,2.0
3,4,lg,1,0,30999,4.40,43.0,led,3840.0,2160.0,1,20.0,2.0,19.2,1,52.0,flipkart,1.0
4,5,philips,1,0,74999,4.05,75.0,qled,3840.0,2160.0,1,30.0,2.0,32.0,1,67.0,amazon,2.0

In [354]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   int32
 3   full_hd            1000 non-null   int32
 4   Price              1000 non-null   int64
 5   Rating             1000 non-null   float64
 6   inches             1000 non-null   float64
 7   display_type       1000 non-null   object
 8   resolution_width   1000 non-null   float64
 9   resolution_height  1000 non-null   float64
 10  wifi               1000 non-null   int32
 11  fast_charging      1000 non-null   float64
 12  ram                1000 non-null   float64
 13  rom                1000 non-null   float64
 14  hdmi_port          1000 non-null   int32
 15  Spec_Score         1000 non-null   float64
 16  Company            1000 non-null   object
 17  usb_port           1000 non-null   float64
dtypes: float64(9), int32(4), int64(2), object(3)
memory usage: 125.1+ KB

In [355]:
df3.to_csv('filling_missing_values.csv')