In [1]:
import pandas as pd
import numpy as np
import re

C:\Users\moham\AppData\Roaming\Python\Python310\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv('Televisions.csv')
df.head()

,Model,Price,Rating,Specs,Company,Spec_Score
0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999",4.65,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,"₹41,999",4.55,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,"₹36,999",4.35,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,"₹30,999",4.40,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,Philips Lumina Series 75 inch Ultra HD 4K Smar...,"₹74,999",4.05,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Dirty Data
### Model Column
1. Should Clear the All data in Lower case
2. Index = 555 has misspelled name 'Black+Decker'
3. Index = 716 has misspelled name 'T-Series' remove '-'

### Price
1. Remove the Rupee Symbol '₹'
2. Remove the camma ','

### Spec_Score
1. Missing Value

### Spec
1. Missing Value
2. Should Clear the All data into Lower Case

# Messy Data
### Model Column
1. Should be data Extract 3 Columns in 'Model' Column 'Brand Name', 'Ultra HD', 'Full HD'

### Specs
##### Extract 12 columns in 'Specs'
1. Inches Column
2. Display Column
3. Resolution Type
4. Resolution Width
5. Resolution Height
6. WIFI Column
7. Speakers Column
8. Fast Charging Column
9. Refresh Rate Column
10. RAM Column
11. ROM Column
12. HDMI PORT Column
13. USB PORT Column

In [4]:
df = df.reset_index()

In [5]:
df.shape

(1000, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       1000 non-null   int64
 1   Model       1000 non-null   object
 2   Price       1000 non-null   object
 3   Rating      1000 non-null   float64
 4   Specs       999 non-null    object
 5   Company     1000 non-null   object
 6   Spec_Score  998 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 54.8+ KB

In [7]:
df.duplicated().sum()

0

In [8]:
df1 = df.copy()

In [9]:
df1.head()

,index,Model,Price,Rating,Specs,Company,Spec_Score
0,0,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999",4.65,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,1,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,"₹41,999",4.55,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,2,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,"₹36,999",4.35,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,3,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,"₹30,999",4.40,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,4,Philips Lumina Series 75 inch Ultra HD 4K Smar...,"₹74,999",4.05,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [10]:
df1['index'] = df1['index'] + 1

In [11]:
df1.head()

,index,Model,Price,Rating,Specs,Company,Spec_Score
0,1,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999",4.65,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,"₹41,999",4.55,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,"₹36,999",4.35,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,"₹30,999",4.40,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,Philips Lumina Series 75 inch Ultra HD 4K Smar...,"₹74,999",4.05,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [12]:
model_name = df1['Model'].str.strip().str.split(' ').str.get(0)
model_pos = df1.columns.get_loc('Model')
df1.insert(model_pos, 'brand', model_name)

In [13]:
df1.head()

,index,brand,Model,Price,Rating,Specs,Company,Spec_Score
0,1,TCL,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999",4.65,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,LG,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,"₹41,999",4.55,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,Xiaomi,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,"₹36,999",4.35,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,LG,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,"₹30,999",4.40,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,Philips,Philips Lumina Series 75 inch Ultra HD 4K Smar...,"₹74,999",4.05,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [14]:
df1['brand'] = df1['brand'].str.replace('+', '')

In [15]:
df1['brand'] = df1['brand'].str.replace('-', '')

In [16]:
df1['brand'] = df1['brand'].str.lower()

In [17]:
df1.head()

,index,brand,Model,Price,Rating,Specs,Company,Spec_Score
0,1,tcl,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999",4.65,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,lg,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,"₹41,999",4.55,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,xiaomi,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,"₹36,999",4.35,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,lg,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,"₹30,999",4.40,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,philips,Philips Lumina Series 75 inch Ultra HD 4K Smar...,"₹74,999",4.05,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [18]:
has_ultra_hd = df1['Model'].str.contains('Ultra HD', case=False, na=False)
model_pos = df1.columns.get_loc('Model')
df1.insert(model_pos, 'ultra_hd', has_ultra_hd)

In [19]:
has_ultra_hd = df1['Model'].str.contains('Full HD', case=False, na=False)
model_pos = df1.columns.get_loc('Model')
df1.insert(model_pos, 'full_hd', has_ultra_hd)

In [20]:
df1.head()

,index,brand,ultra_hd,full_hd,Model,Price,Rating,Specs,Company,Spec_Score
0,1,tcl,True,False,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),"₹42,999",4.65,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,lg,True,False,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,"₹41,999",4.55,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,xiaomi,True,False,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,"₹36,999",4.35,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,lg,True,False,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,"₹30,999",4.40,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,philips,True,False,Philips Lumina Series 75 inch Ultra HD 4K Smar...,"₹74,999",4.05,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [21]:
df1['Price'] = df1['Price'].str.replace('₹', '')

In [22]:
df1['Price'] = df1['Price'].str.replace(',', '')

In [23]:
df1.head()

,index,brand,ultra_hd,full_hd,Model,Price,Rating,Specs,Company,Spec_Score
0,1,tcl,True,False,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),42999,4.65,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,lg,True,False,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,41999,4.55,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,xiaomi,True,False,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,36999,4.35,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,lg,True,False,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,30999,4.40,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,philips,True,False,Philips Lumina Series 75 inch Ultra HD 4K Smar...,74999,4.05,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [24]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       1000 non-null   int64
 1   brand       1000 non-null   object
 2   ultra_hd    1000 non-null   bool
 3   full_hd     1000 non-null   bool
 4   Model       1000 non-null   object
 5   Price       1000 non-null   object
 6   Rating      1000 non-null   float64
 7   Specs       999 non-null    object
 8   Company     1000 non-null   object
 9   Spec_Score  998 non-null    float64
dtypes: bool(2), float64(2), int64(1), object(5)
memory usage: 64.6+ KB

In [25]:
df1['Price'] = df1['Price'].astype(int)

In [26]:
inches = df1['Specs'].str.split(',').str.get(0)
model_pos = df1.columns.get_loc('Specs')
df1.insert(model_pos, 'inches', inches)

In [27]:
df1['inches'] = df1['inches'].str.split(' ').str.get(0)

In [28]:
display = df1['Specs'].str.split(' ').str.get(2)
model_pos = df1.columns.get_loc('Specs')
df1.insert(model_pos, 'display_type', display)

In [29]:
df1.head()

,index,brand,ultra_hd,full_hd,Model,Price,Rating,inches,display_type,Specs,Company,Spec_Score
0,1,tcl,True,False,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),42999,4.65,55,QLED,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,lg,True,False,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,41999,4.55,55,LED,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,xiaomi,True,False,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,36999,4.35,55,QLED,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,lg,True,False,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,30999,4.40,43,LED,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,philips,True,False,Philips Lumina Series 75 inch Ultra HD 4K Smar...,74999,4.05,75,QLED,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [30]:
df1['display_type'] = df1['display_type'].str.replace('Mini', 'MiniLED')

In [31]:
df1['display_type'] = df1['display_type'].replace('Resolution,', np.nan)

In [32]:
df1['display_type'].value_counts()

display_type
LED        441
QLED       391
MiniLED    111
OLED        41
Micro        5
QNED         5
LCD          2
Laser        1
             1
Name: count, dtype: int64

In [33]:
df1['display_type'] = df1['display_type'].str.lower()

In [34]:
df1.head()

,index,brand,ultra_hd,full_hd,Model,Price,Rating,inches,display_type,Specs,Company,Spec_Score
0,1,tcl,True,False,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),42999,4.65,55,qled,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,lg,True,False,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,41999,4.55,55,led,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,xiaomi,True,False,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,36999,4.35,55,qled,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,lg,True,False,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,30999,4.40,43,led,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,philips,True,False,Philips Lumina Series 75 inch Ultra HD 4K Smar...,74999,4.05,75,qled,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [35]:
df1.isnull().sum()

index           0
brand           0
ultra_hd        0
full_hd         0
Model           0
Price           0
Rating          0
inches          1
display_type    2
Specs           1
Company         0
Spec_Score      2
dtype: int64

In [36]:
width = df1['Specs'].str.split('x').str.get(0).str.split(',').str.get(2)
model_pos = df1.columns.get_loc('Specs')
df1.insert(model_pos, 'resolution_width', width)

In [37]:
df1['resolution_width'].value_counts()

resolution_width
3840                              751
1920                               85
7680                                4
EthernetSmart TV60 W OutputHDR      1
Name: count, dtype: int64

In [38]:
width = df1['Specs'].str.split('x').str.get(1)
model_pos = df1.columns.get_loc('Specs')
df1.insert(model_pos, 'resolution_height', width)

In [39]:
df1['resolution_height'].value_counts()

resolution_height
 2160 pi                                                                                      752
 768 pi                                                                                       156
 1080 pi                                                                                       85
 4320 pi                                                                                        4
Prime VideoDisney+HotstarYoutubeOperating System: Google TVResolution: Ultra HD (4K) 3840       1
Name: count, dtype: int64

In [40]:
df1.head()

,index,brand,ultra_hd,full_hd,Model,Price,Rating,inches,display_type,resolution_width,resolution_height,Specs,Company,Spec_Score
0,1,tcl,True,False,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),42999,4.65,55,qled,3840,2160 pi,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,lg,True,False,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,41999,4.55,55,led,3840,2160 pi,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,xiaomi,True,False,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,36999,4.35,55,qled,3840,2160 pi,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,lg,True,False,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,30999,4.40,43,led,3840,2160 pi,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,philips,True,False,Philips Lumina Series 75 inch Ultra HD 4K Smar...,74999,4.05,75,qled,3840,2160 pi,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [41]:
df1.isnull().sum()

index                  0
brand                  0
ultra_hd               0
full_hd                0
Model                  0
Price                  0
Rating                 0
inches                 1
display_type           2
resolution_width     159
resolution_height      2
Specs                  1
Company                0
Spec_Score             2
dtype: int64

In [42]:
df1['resolution_height'] = df1['resolution_height'].replace(r'.*Prime VideoDisney.*', np.nan, regex=True)

In [43]:
df1['resolution_height'].value_counts()

resolution_height
2160 pi    752
768 pi     156
1080 pi     85
4320 pi      4
Name: count, dtype: int64

In [44]:
df1['resolution_width'] = df1['resolution_width'].replace(r'.*EthernetSmart.*', np.nan, regex=True)

In [45]:
df1['resolution_width'].value_counts()

resolution_width
3840     751
1920      85
7680       4
Name: count, dtype: int64

In [46]:
df1.isnull().sum()

index                  0
brand                  0
ultra_hd               0
full_hd                0
Model                  0
Price                  0
Rating                 0
inches                 1
display_type           2
resolution_width     160
resolution_height      3
Specs                  1
Company                0
Spec_Score             2
dtype: int64

In [47]:
df1['resolution_height'] = df1['resolution_height'].str.replace('pi', '')

In [48]:
df1['resolution_height'].value_counts()

resolution_height
2160     752
768      156
1080      85
4320       4
Name: count, dtype: int64

In [49]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   bool
 3   full_hd            1000 non-null   bool
 4   Model              1000 non-null   object
 5   Price              1000 non-null   int32
 6   Rating             1000 non-null   float64
 7   inches             999 non-null    object
 8   display_type       998 non-null    object
 9   resolution_width   840 non-null    object
 10  resolution_height  997 non-null    object
 11  Specs              999 non-null    object
 12  Company            1000 non-null   object
 13  Spec_Score         998 non-null    float64
dtypes: bool(2), float64(2), int32(1), int64(1), object(8)
memory usage: 91.9+ KB

In [50]:
wifi = df1['Specs'].str.contains('Wifi', case=False, na=False, flags=0)
model_pos = df1.columns.get_loc('Specs')
df1.insert(model_pos, 'wifi', wifi)

In [51]:
pattern = '\d\d\sW'
fast = df1['Specs'].apply(lambda x: re.findall(pattern, str(x)))
model_pos = df1.columns.get_loc('Specs')
df1.insert(model_pos, 'fast_charging', fast)

In [52]:
df1.head()

,index,brand,ultra_hd,full_hd,Model,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,Specs,Company,Spec_Score
0,1,tcl,True,False,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),42999,4.65,55,qled,3840,2160,True,[20 W],"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,lg,True,False,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,41999,4.55,55,led,3840,2160,True,[20 W],"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,xiaomi,True,False,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,36999,4.35,55,qled,3840,2160,True,[34 W],"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,lg,True,False,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,30999,4.40,43,led,3840,2160,True,[20 W],"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,philips,True,False,Philips Lumina Series 75 inch Ultra HD 4K Smar...,74999,4.05,75,qled,3840,2160,True,[30 W],"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [53]:
df1['fast_charging'] = df1['fast_charging'].apply(', '.join)

In [54]:
df1['fast_charging'] = df1['fast_charging'].replace('', np.nan)

In [55]:
df1['fast_charging'].isnull().sum()

10

In [56]:
df1['fast_charging'] = df1['fast_charging'].str.replace(' W', '')

In [57]:
pattern = '\d\sGB\sRAM'
ram = df1['Specs'].apply(lambda x: re.findall(pattern, str(x)))
model_pos = df1.columns.get_loc('Specs')
df1.insert(model_pos, 'ram', ram)

In [58]:
df1['ram'] = df1['ram'].apply(','.join)

In [59]:
df1['ram'] = df1['ram'].replace('', np.nan)

In [60]:
df1['ram'].value_counts()

ram
2 GB RAM    275
1 GB RAM     74
3 GB RAM     56
5 GB RAM     35
4 GB RAM      3
Name: count, dtype: int64

In [61]:
df1['ram'].isnull().sum()

557

In [62]:
df1['ram'] = df1['ram'].str.replace(' GB', '').str.replace(' RAM', '')

In [63]:
df1['ram'].value_counts()

ram
2    275
1     74
3     56
5     35
4      3
Name: count, dtype: int64

In [64]:
df1.head()

,index,brand,ultra_hd,full_hd,Model,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,Specs,Company,Spec_Score
0,1,tcl,True,False,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),42999,4.65,55,qled,3840,2160,True,20,2,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,lg,True,False,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,41999,4.55,55,led,3840,2160,True,20,2,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,xiaomi,True,False,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,36999,4.35,55,qled,3840,2160,True,34,2,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,lg,True,False,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,30999,4.40,43,led,3840,2160,True,20,2,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,philips,True,False,Philips Lumina Series 75 inch Ultra HD 4K Smar...,74999,4.05,75,qled,3840,2160,True,30,2,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [65]:
pattern2 = '\d\d\s\w\w\sStorageHDR'
rom = df['Specs'].apply(lambda x: re.findall(pattern2, str(x)))
model_pos = df1.columns.get_loc('Specs')
df1.insert(model_pos, 'rom', rom)

In [66]:
df1['rom'] = df1['rom'].apply(','.join)

In [67]:
df1['rom'].value_counts()

rom
                    648
16 GB StorageHDR    183
32 GB StorageHDR    149
64 GB StorageHDR     20
Name: count, dtype: int64

In [68]:
df1['rom'] = df1['rom'].replace('', np.nan)

In [69]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   bool
 3   full_hd            1000 non-null   bool
 4   Model              1000 non-null   object
 5   Price              1000 non-null   int32
 6   Rating             1000 non-null   float64
 7   inches             999 non-null    object
 8   display_type       998 non-null    object
 9   resolution_width   840 non-null    object
 10  resolution_height  997 non-null    object
 11  wifi               1000 non-null   bool
 12  fast_charging      990 non-null    object
 13  ram                443 non-null    object
 14  rom                352 non-null    object
 15  Specs              999 non-null    object
 16  Company            1000 non-null   object
 17  Spec_Score         998 non-null    float64
dtypes: bool(3), float64(2), int32(1), int64(1), object(11)
memory usage: 116.3+ KB

In [70]:
df1['rom'] = df1['rom'].str.replace('GB', '').str.replace('StorageHDR', '')

In [71]:
df1['rom'].value_counts()

rom
16      183
32      149
64       20
Name: count, dtype: int64

In [72]:
df1.head()

,index,brand,ultra_hd,full_hd,Model,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,rom,Specs,Company,Spec_Score
0,1,tcl,True,False,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),42999,4.65,55,qled,3840,2160,True,20,2,16,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0
1,2,lg,True,False,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,41999,4.55,55,led,3840,2160,True,20,2,NaN,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0
2,3,xiaomi,True,False,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,36999,4.35,55,qled,3840,2160,True,34,2,32,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0
3,4,lg,True,False,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,30999,4.40,43,led,3840,2160,True,20,2,NaN,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0
4,5,philips,True,False,Philips Lumina Series 75 inch Ultra HD 4K Smar...,74999,4.05,75,qled,3840,2160,True,30,2,32,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0

In [73]:
# df1['inches'] = df1['inches'].astype(int)
# df1['resolution_width'] = df1['resolution_width'].astype(int)
# df1['resolution_height'] = df1['resolution_height'].astype(int)
# df1['fast_charging'] = df1['fast_charging'].astype(int)
# df1['rom'] = df1['rom'].astype(int)
# df1['ram'] = df1['ram'].astype(int)

In [74]:
hdmi = df1['Specs'].str.contains('HDMI Ports', case=False, na=False)
model_pos = df1.columns.get_loc('Specs')
df1.insert(model_pos, 'hdmi_port', hdmi)

In [75]:
df1['hdmi_port'].isnull().sum()

0

In [76]:
df1['usb_port'] = df1['Specs'].str.extract(r'(\d+)\sUSB\sPorts')

In [77]:
df1['usb_port'].value_counts()

usb_port
2    725
1    227
3     33
4      1
Name: count, dtype: int64

In [78]:
df1['usb_port'].isnull().sum()

14

In [79]:
df1.head()

,index,brand,ultra_hd,full_hd,Model,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,rom,hdmi_port,Specs,Company,Spec_Score,usb_port
0,1,tcl,True,False,TCL P7K 55 inch Ultra HD 4K Smart QLED TV (55P7K),42999,4.65,55,qled,3840,2160,True,20,2,16,True,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",flipkart,58.0,2
1,2,lg,True,False,LG UA8200 55 inch Ultra HD 4K Smart LED TV (55...,41999,4.55,55,led,3840,2160,True,20,2,NaN,True,"55 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,55.0,1
2,3,xiaomi,True,False,Xiaomi FX Pro Series 55 inch Ultra HD 4K Smar...,36999,4.35,55,qled,3840,2160,True,34,2,32,True,"55 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,55.0,2
3,4,lg,True,False,LG UA8200 43 inch Ultra HD 4K Smart LED TV (43...,30999,4.40,43,led,3840,2160,True,20,2,NaN,True,"43 in, LED TV4K Resolution, 3840 x 2160 pixels...",flipkart,52.0,1
4,5,philips,True,False,Philips Lumina Series 75 inch Ultra HD 4K Smar...,74999,4.05,75,qled,3840,2160,True,30,2,32,True,"75 in, QLED TV4K Resolution, 3840 x 2160 pixel...",amazon,67.0,2

In [80]:
df2 = df1.drop(columns=['Model', 'Specs'])

In [81]:
df2.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,resolution_width,resolution_height,wifi,fast_charging,ram,rom,hdmi_port,Company,Spec_Score,usb_port
0,1,tcl,True,False,42999,4.65,55,qled,3840,2160,True,20,2,16,True,flipkart,58.0,2
1,2,lg,True,False,41999,4.55,55,led,3840,2160,True,20,2,NaN,True,flipkart,55.0,1
2,3,xiaomi,True,False,36999,4.35,55,qled,3840,2160,True,34,2,32,True,amazon,55.0,2
3,4,lg,True,False,30999,4.40,43,led,3840,2160,True,20,2,NaN,True,flipkart,52.0,1
4,5,philips,True,False,74999,4.05,75,qled,3840,2160,True,30,2,32,True,amazon,67.0,2

In [82]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              1000 non-null   int64
 1   brand              1000 non-null   object
 2   ultra_hd           1000 non-null   bool
 3   full_hd            1000 non-null   bool
 4   Price              1000 non-null   int32
 5   Rating             1000 non-null   float64
 6   inches             999 non-null    object
 7   display_type       998 non-null    object
 8   resolution_width   840 non-null    object
 9   resolution_height  997 non-null    object
 10  wifi               1000 non-null   bool
 11  fast_charging      990 non-null    object
 12  ram                443 non-null    object
 13  rom                352 non-null    object
 14  hdmi_port          1000 non-null   bool
 15  Company            1000 non-null   object
 16  Spec_Score         998 non-null    float64
 17  usb_port           986 non-null    object
dtypes: bool(4), float64(2), int32(1), int64(1), object(10)
memory usage: 109.5+ KB

In [84]:
df2.to_csv('cleaned_data.csv')